GET http://localhost:3000/auth?redirect=http://123.com

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "phone":"17828228827",
    "password":"youling"
}

###
GET http://localhost:3000/login

###
GET http://localhost:3000/verifyCode?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMSIsInBob25lIjoiMTc4MjgyMjg4MjciLCJwYXNzd29yZCI6InlvdWxpbmcifSwiaWF0IjoxNjA0NDc0ODczLCJleHAiOjE2MDQ0NzU0NzN9.dcKdu3KKVTJNZSLBnv36DpOw6D3M9pzNaOgljq4D2BM
